/* Automatically generated by './build/bin/build-entry.js' */

import Collapse from '../packages/collapse/index.js'
import CollapsePanel from '../packages/collapse-panel/index.js'
import Rollnotice from '../packages/rollnotice/index.js'
import RollnoticeItem from '../packages/rollnotice-item/index.js'
import Sendcode from '../packages/sendcode/index.js'
import Sort from '../packages/sort/index.js'
import TradeSlider from '../packages/trade-slider/index.js'

const components = [
  Collapse,
  CollapsePanel,
  Rollnotice,
  RollnoticeItem,
  Sendcode,
  Sort,
  TradeSlider
]

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  })
}

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue)
}

export default {
  version: '0.0.6',
  install,
  Collapse,
  CollapsePanel,
  Rollnotice,
  RollnoticeItem,
  Sendcode,
  Sort,
  TradeSlider
}
